using Microsoft.EntityFrameworkCore.Migrations;

namespace Ecommwebapi.Migrations
{
    public partial class AutogeneratedIds : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
